import 'dart:convert';

import '../../core/config/app_config.dart';
import '../../domain/server_models.dart';

/// Renders the GitHub Actions workflow that runs one VoxelOps server.
///
/// Values are emitted as JSON strings (valid YAML) to avoid quoting bugs. Secrets are referenced
/// by name only; their values are stored in GitHub Actions secrets, never in the repository.
class WorkflowTemplate {
  const WorkflowTemplate._();

  static String render({
    required ServerRecord record,
    required RuntimeSettings runtime,
    required bool tailscaleEnabled,
  }) {
    final hostname = _hostname(record);
    final runsOn = record.runnerLabel.trim().isEmpty ? 'ubuntu-latest' : record.runnerLabel.trim();
    final buffer = StringBuffer()
      ..writeln('# Generated by VoxelOps. Changes made here are overwritten when the server is re-synced.')
      ..writeln('name: ${_q('VoxelOps - ${record.name}')}')
      ..writeln('on:')
      ..writeln('  workflow_dispatch:')
      ..writeln('permissions:')
      ..writeln('  contents: read')
      ..writeln('  actions: write')
      ..writeln('concurrency:')
      ..writeln('  group: ${_q('voxelops-${record.id}')}')
      ..writeln('  cancel-in-progress: false')
      ..writeln('jobs:')
      ..writeln('  server:')
      ..writeln('    name: ${_q('Minecraft ${record.name}')}')
      ..writeln('    runs-on: ${_q(runsOn)}')
      ..writeln('    timeout-minutes: 350')
      ..writeln('    env:')
      ..writeln('      VOXEL_SERVER_ID: ${_q(record.id)}')
      ..writeln('      VOXEL_SERVER_NAME: ${_q(record.name)}')
      ..writeln('      VOXEL_SOFTWARE: ${_q(record.software.runnerId)}')
      ..writeln('      VOXEL_MC_VERSION: ${_q(record.minecraftVersion)}')
      ..writeln('      VOXEL_LOADER_VERSION: ${_q(record.loaderVersion)}')
      ..writeln('      VOXEL_RUN_LIMIT_MINUTES: ${_q('330')}')
      ..writeln('      VOXEL_WORKFLOW_FILE: ${_q(AppConfig.workflowFileName)}')
      ..writeln('      VOXEL_TAILSCALE_HOSTNAME: ${_q(hostname)}')
      ..writeln('      VOXEL_TAILSCALE_ENABLED: ${_q(tailscaleEnabled ? 'true' : 'false')}')
      ..writeln('      VOXEL_RUNTIME_DEFAULTS: ${_q(jsonEncode(runtime.toJson()))}')
      ..writeln('    steps:')
      ..writeln('      - name: Check out repository')
      ..writeln('        uses: actions/checkout@v7')
      ..writeln('        with:')
      ..writeln('          persist-credentials: false')
      ..writeln('      - name: Set up Java')
      ..writeln('        uses: actions/setup-java@v6')
      ..writeln('        with:')
      ..writeln('          distribution: temurin')
      ..writeln('          java-version: ${_q('${record.javaMajor}')}');
    if (tailscaleEnabled) {
      buffer
        ..writeln('      - name: Join Tailscale')
        ..writeln('        uses: tailscale/github-action@v4')
        ..writeln('        with:')
        ..writeln('          oauth-client-id: \${{ secrets.TS_OAUTH_CLIENT_ID }}')
        ..writeln('          oauth-secret: \${{ secrets.TS_OAUTH_SECRET }}')
        ..writeln('          tags: ${_q(AppConfig.defaultTailscaleTag)}')
        ..writeln('          hostname: ${_q(hostname)}');
    }
    buffer
      ..writeln('      - name: Run VoxelOps runner')
      ..writeln('        env:')
      ..writeln('          VOXEL_DRIVE_FOLDER_ID: \${{ secrets.VOXEL_DRIVE_FOLDER_ID }}')
      ..writeln('          GDRIVE_CLIENT_ID: \${{ secrets.GDRIVE_CLIENT_ID }}')
      ..writeln('          GDRIVE_REFRESH_TOKEN: \${{ secrets.GDRIVE_REFRESH_TOKEN }}')
      ..writeln('          GITHUB_TOKEN: \${{ github.token }}')
      ..writeln('        run: python3 ${AppConfig.runnerRepoPath}');
    return buffer.toString();
  }

  /// DNS label: lowercase letters, digits and dashes, max 63 characters.
  static String hostname(ServerRecord record) => _hostname(record);

  static String _hostname(ServerRecord record) {
    final suffix = record.id.replaceAll(RegExp(r'[^a-z0-9]'), '').toLowerCase();
    final tail = suffix.length > 8 ? suffix.substring(suffix.length - 8) : suffix;
    final name = record.name.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]+'), '-').replaceAll(RegExp(r'^-+|-+$'), '');
    final short = name.length > 24 ? name.substring(0, 24).replaceAll(RegExp(r'-+$'), '') : name;
    final value = short.isEmpty ? '${AppConfig.tailscaleHostPrefix}-$tail' : '${AppConfig.tailscaleHostPrefix}-$short-$tail';
    return value.length > 63 ? value.substring(0, 63) : value;
  }

  static String _q(String value) => jsonEncode(value);
}
